// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://llnjcsanbtxrjisontsd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxsbmpjc2FuYnR4cmppc29udHNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MTI0MzEsImV4cCI6MjA2MTA4ODQzMX0.lo13jAtQwGcMHbdijCXM-qujz-pHpYVOR_90V4HQdFI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);